# Stage 1: Build Stage
FROM node:18-alpine as builder

WORKDIR /app

COPY . /app

RUN yarn install --production && yarn build

# Stage 2: Production Stage
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/package.json /app/yarn.lock ./

COPY --from=builder /app/dist ./dist

RUN yarn install --production

EXPOSE 3000

CMD ["node", "./build/index.js"]